services:
  app:
    image: plant:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - DB_HOST=docker.host.internal
    ports:
      - '4321:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
